### ISSUE TITLE
errors when using with Gina blame

### ISSUE THREAD

**Issue by prabirshrestha** [runoshun/tscompletejob#5]
Install https://github.com/lambdalisue/gina.vim

Then in typescript file `:Gina blame :`

![image](https://cloud.githubusercontent.com/assets/287744/23563150/44829dae-fffa-11e6-962d-ce9f37fe11c1.png)

**Comment by prabirshrestha** [comment]
Seems like a bug in gina filed a bug there at https://github.com/lambdalisue/gina.vim/issues/60

**Comment by lambdalisue** [comment]
It is not gina.vim's fault. tscompletejob should

1. Ignore buffer name which start from a protocol (e.g. `http://` or `gina://` or `fugitive://` or ....)
2. Ignore buffer which is not modifiable

**Comment by runoshun** [comment]
Sorry for late reply. I fix handling of remote filepath. 

@prabirshrestha 
Sorry, I have fixed it without noticing your PR #8. In my code, buffers which starts with protocols are used as it is, instead of ignore.
If you want to ignore particular name of buffer, please add regexp to `g:tscompletejob_ignore_file_patters`.

**Comment by prabirshrestha** [comment]
seems to work now. Thanks for the fix.
